### ISSUE TITLE
add typescript support

### ISSUE THREAD

**Issue by masx200** [sachinchoolur/replace-jquery#10]
add typescript support

```
pnpx replace-jquery "src/*.ts" out.js
Finding jQuery function reference in src/addfetch.ts ...
Finding jQuery function reference in src/cachepromise.ts ...
(node:4227) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token <
    at Espree.raise (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/espree@7.3.1/node_modules/espree/lib/espree.js:190:25)
    at Espree.unexpected (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/espree@7.3.1/node_modules/espree/lib/espree.js:235:18)
    at Espree.pp.expect (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/acorn@7.4.1/node_modules/acorn/dist/acorn.js:692:28)
    at Espree.pp$1.parseFunctionParams (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/acorn@7.4.1/node_modules/acorn/dist/acorn.js:1303:10)
    at Espree.pp$1.parseFunction (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/acorn@7.4.1/node_modules/acorn/dist/acorn.js:1293:10)
    at Espree.pp$1.parseFunctionStatement (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/acorn@7.4.1/node_modules/acorn/dist/acorn.js:992:17)
    at Espree.pp$1.parseStatement (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/acorn@7.4.1/node_modules/acorn/dist/acorn.js:839:19)
    at Espree.pp$1.parseExport (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/acorn@7.4.1/node_modules/acorn/dist/acorn.js:1458:31)
    at Espree.pp$1.parseStatement (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/acorn@7.4.1/node_modules/acorn/dist/acorn.js:872:74)
    at Espree.pp$1.parseTopLevel (/data/data/com.termux/files/usr/pnpm-global/5/node_modules/.pnpm/acorn@7.4.1/node_modules/acorn/dist/acorn.js:755:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4227) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sachinchoolur** [comment]
Hye @masx200,

Sorry for the late reply. Yes, it should be possible. But, we'll have to re-write all plain JS jQuery alternative functions in typescript. This is a little bit of work. I'll consider adding TS support when I get time. 
Closing this issue as this is a long-term goal.
